### ISSUE TITLE
Pulsar new feature: enable client code to access atacseq experiment identifiers

### ISSUE THREAD

**Issue by twang15** [nathankw/pulsar_lims#119]
Currently, Pulsar does not allow client code to access atacseq experiment identifiers.
But client code needs this information in **post_fastq_file** to enable differential handling for data submission.

**Comment by twang15** [comment]
The solution is to serialize atacseq_id in Pulsar.

**Comment by twang15** [comment]
2021-03-10T23:28:33.329058+00:00 app[web.1]: Started POST "/api/libraries/find_by" for 171.67.92.58 at 2021-03-10 23:28:33 +0000
2021-03-10T23:28:33.331581+00:00 app[web.1]: Processing by Api::LibrariesController#find_by as JSON
2021-03-10T23:28:33.331613+00:00 app[web.1]: Parameters: {"find_by"=>{"id"=>10721}, "library"=>{}}
2021-03-10T23:28:33.331754+00:00 app[web.1]: Can't verify CSRF token authenticity
2021-03-10T23:28:33.334760+00:00 app[web.1]: User Load (2.0ms)  SELECT  "users".* FROM "users" WHERE "users"."api_key" = $1  ORDER BY "users"."last_name" ASC, "users"."first_name" ASC LIMIT 1  [["api_key", "7f25345276e5e7128d69dd83c4732085"]]
2021-03-10T23:28:33.335303+00:00 app[web.1]: {"id"=>10721}
2021-03-10T23:28:33.337280+00:00 app[web.1]: Library Load (1.7ms)  SELECT  "libraries".* FROM "libraries" WHERE "libraries"."id" = $1 LIMIT 1  [["id", 10721]]
2021-03-10T23:28:33.355350+00:00 app[web.1]: Completed 500 Internal Server Error in 24ms (ActiveRecord: 3.6ms)
2021-03-10T23:28:33.356285+00:00 app[web.1]:
2021-03-10T23:28:33.356286+00:00 app[web.1]: NoMethodError (undefined method `updated_ait' for #<Library:0x0000000008c86178>
2021-03-10T23:28:33.356288+00:00 app[web.1]: Did you mean?  updated_at
2021-03-10T23:28:33.356288+00:00 app[web.1]: updated_at?
2021-03-10T23:28:33.356288+00:00 app[web.1]: updated_at=):
2021-03-10T23:28:33.356289+00:00 app[web.1]: app/controllers/application_controller.rb:108:in `find_by'
2021-03-10T23:28:33.356289+00:00 app[web.1]: app/controllers/api/libraries_controller.rb:9:in `find_by'

**Comment by twang15** [comment]
git format-patch 79147c554f12ac578..add3bd76caf94be6cdc603 --stdout >patch.issue119
cp patch.issue119 /Users/tao1/Documents/2020Spring/Job/RailApps/encode/pulsar_lims/app/
cd /Users/tao1/Documents/2020Spring/Job/RailApps/encode/pulsar_lims/app
git am patch.issue119


Error:

tao1@Taos-MBP app % git am patch.issue119
**fatal: previous rebase directory .git/rebase-apply still exists but mbox given.**

**Comment by twang15** [comment]
Solution:
git am --abort

https://stackoverflow.com/questions/24121709/git-error-previous-rebase-directory-git-rebase-apply-still-exists-but-mbox-giv

**Comment by twang15** [comment]
then

git push prod-heroku master
git am patch.issue119
